name: .NET Core Desktop

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug, Release]
        runner:
          - windows-2022
          - ubuntu-24.04
          - macos-15

    runs-on: ${{ matrix.runner }}

    env:
      Solution_Name: KisaragiMarine.HelloWorld.sln

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Build
      run: |
        dotnet build

    
