# See also: https://one-sthead.hatenablog.com/entry/2021/02/02/220919
name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Tag'
        required: true
        type: string

jobs:
  publish:
    env:
      TARGET_TAG: ${{ inputs.tag }}
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        ref: ${{ env.TARGET_TAG }}
    
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    
    - name: Build
      run: dotnet build --configuration Release

    - name: Generate nuget package.
      run: dotnet pack --configuration Release -o nupkg
    
    - name: Publish to nuget
      run: find . -type f -name *.nupkg -print0 | xargs -0 -I pkg dotnet nuget push pkg -k "$nuget_api_key" -s "https://api.nuget.org/v3/index.json" --skip-duplicate
      env:
        nuget_api_key: ${{ secrets.NUGET_API_KEY }}
      working-directory: ./nupkg
